//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogretmen_Asistan {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Ayarlarim : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ayarlarim defaultInstance = ((Ayarlarim)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ayarlarim())));
        
        public static Ayarlarim Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string zildosyayolu {
            get {
                return ((string)(this["zildosyayolu"]));
            }
            set {
                this["zildosyayolu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string sayacdosyayolu {
            get {
                return ((string)(this["sayacdosyayolu"]));
            }
            set {
                this["sayacdosyayolu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baybars KIZILKAYA")]
        public string heroname {
            get {
                return ((string)(this["heroname"]));
            }
            set {
                this["heroname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08:30")]
        public string ilkzil {
            get {
                return ((string)(this["ilkzil"]));
            }
            set {
                this["ilkzil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:10")]
        public string ilkzilcikis {
            get {
                return ((string)(this["ilkzilcikis"]));
            }
            set {
                this["ilkzilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:20")]
        public string ikizil {
            get {
                return ((string)(this["ikizil"]));
            }
            set {
                this["ikizil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:00")]
        public string ikizilcikis {
            get {
                return ((string)(this["ikizilcikis"]));
            }
            set {
                this["ikizilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:10")]
        public string uczil {
            get {
                return ((string)(this["uczil"]));
            }
            set {
                this["uczil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:50")]
        public string uczilcikis {
            get {
                return ((string)(this["uczilcikis"]));
            }
            set {
                this["uczilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11:00")]
        public string dortzil {
            get {
                return ((string)(this["dortzil"]));
            }
            set {
                this["dortzil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11:40")]
        public string dortzilcikis {
            get {
                return ((string)(this["dortzilcikis"]));
            }
            set {
                this["dortzilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:20")]
        public string beszil {
            get {
                return ((string)(this["beszil"]));
            }
            set {
                this["beszil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13:00")]
        public string beszilcikis {
            get {
                return ((string)(this["beszilcikis"]));
            }
            set {
                this["beszilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13:10")]
        public string altizil {
            get {
                return ((string)(this["altizil"]));
            }
            set {
                this["altizil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13:50")]
        public string altizilcikis {
            get {
                return ((string)(this["altizilcikis"]));
            }
            set {
                this["altizilcikis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string zilchek {
            get {
                return ((string)(this["zilchek"]));
            }
            set {
                this["zilchek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string zilses {
            get {
                return ((string)(this["zilses"]));
            }
            set {
                this["zilses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Anaform {
            get {
                return ((string)(this["Anaform"]));
            }
            set {
                this["Anaform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Yarismaform {
            get {
                return ((string)(this["Yarismaform"]));
            }
            set {
                this["Yarismaform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Passward {
            get {
                return ((string)(this["Passward"]));
            }
            set {
                this["Passward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Oncelik {
            get {
                return ((string)(this["Oncelik"]));
            }
            set {
                this["Oncelik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string kisaZil {
            get {
                return ((string)(this["kisaZil"]));
            }
            set {
                this["kisaZil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string zildosyayolu2 {
            get {
                return ((string)(this["zildosyayolu2"]));
            }
            set {
                this["zildosyayolu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sosyal Bilgiler")]
        public string pz1 {
            get {
                return ((string)(this["pz1"]));
            }
            set {
                this["pz1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string pz2 {
            get {
                return ((string)(this["pz2"]));
            }
            set {
                this["pz2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string pz3 {
            get {
                return ((string)(this["pz3"]));
            }
            set {
                this["pz3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matematik")]
        public string pz4 {
            get {
                return ((string)(this["pz4"]));
            }
            set {
                this["pz4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matematik")]
        public string pz5 {
            get {
                return ((string)(this["pz5"]));
            }
            set {
                this["pz5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Müzik")]
        public string pz6 {
            get {
                return ((string)(this["pz6"]));
            }
            set {
                this["pz6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sosyal Bilgiler")]
        public string sl1 {
            get {
                return ((string)(this["sl1"]));
            }
            set {
                this["sl1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sosyal Bilgiler")]
        public string sl2 {
            get {
                return ((string)(this["sl2"]));
            }
            set {
                this["sl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matematik")]
        public string sl3 {
            get {
                return ((string)(this["sl3"]));
            }
            set {
                this["sl3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string sl4 {
            get {
                return ((string)(this["sl4"]));
            }
            set {
                this["sl4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string sl5 {
            get {
                return ((string)(this["sl5"]));
            }
            set {
                this["sl5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oyun ve Fiziki Etkinlik")]
        public string sl6 {
            get {
                return ((string)(this["sl6"]));
            }
            set {
                this["sl6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Din Kültürü ve Ahlak Bilgisi")]
        public string cr1 {
            get {
                return ((string)(this["cr1"]));
            }
            set {
                this["cr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Din Kültürü ve Ahlak Bilgisi")]
        public string cr2 {
            get {
                return ((string)(this["cr2"]));
            }
            set {
                this["cr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fen Bilimleri")]
        public string cr3 {
            get {
                return ((string)(this["cr3"]));
            }
            set {
                this["cr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string cr4 {
            get {
                return ((string)(this["cr4"]));
            }
            set {
                this["cr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string cr5 {
            get {
                return ((string)(this["cr5"]));
            }
            set {
                this["cr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oyun ve Fiziki Etkinlik")]
        public string cr6 {
            get {
                return ((string)(this["cr6"]));
            }
            set {
                this["cr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yabancı Dil")]
        public string pr1 {
            get {
                return ((string)(this["pr1"]));
            }
            set {
                this["pr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yabancı Dil")]
        public string pr2 {
            get {
                return ((string)(this["pr2"]));
            }
            set {
                this["pr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fen Bilimleri")]
        public string pr3 {
            get {
                return ((string)(this["pr3"]));
            }
            set {
                this["pr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fen Bilimleri")]
        public string pr4 {
            get {
                return ((string)(this["pr4"]));
            }
            set {
                this["pr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("İnsan Hakları Yurttaşlık ve Demokrasi")]
        public string pr5 {
            get {
                return ((string)(this["pr5"]));
            }
            set {
                this["pr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("İnsan Hakları Yurttaşlık ve Demokrasi")]
        public string pr6 {
            get {
                return ((string)(this["pr6"]));
            }
            set {
                this["pr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string cm1 {
            get {
                return ((string)(this["cm1"]));
            }
            set {
                this["cm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Türkçe")]
        public string cm2 {
            get {
                return ((string)(this["cm2"]));
            }
            set {
                this["cm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matematik")]
        public string cm3 {
            get {
                return ((string)(this["cm3"]));
            }
            set {
                this["cm3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matematik")]
        public string cm4 {
            get {
                return ((string)(this["cm4"]));
            }
            set {
                this["cm4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trafik Güvenliği")]
        public string cm5 {
            get {
                return ((string)(this["cm5"]));
            }
            set {
                this["cm5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Görsel Sanatlar")]
        public string cm6 {
            get {
                return ((string)(this["cm6"]));
            }
            set {
                this["cm6"] = value;
            }
        }
    }
}
